plugins {
    id 'multiloader-loader'
    id 'fabric-loom'
    id "me.modmuss50.mod-publish-plugin"
}

repositories {
    maven {
        name = "Sleeping Town"
        url = "https://repo.sleeping.town/"
    }
    maven {
        name = "Ladysnake Libs"
        url = 'https://maven.ladysnake.org/releases'
    }
    maven {
        // Cloth Config, pulled in transitively by Accessories
        name = "Shedaniel"
        url = 'https://maven.shedaniel.me/'
    }
}

dependencies {
    minecraft("com.mojang:minecraft:${minecraft_version}")
    mappings loom.layered {
        officialMojangMappings()
        parchment("org.parchmentmc.data:parchment-${parchment_minecraft}:${parchment_version}@zip")
    }
    modImplementation("net.fabricmc:fabric-loader:${fabric_loader_version}")
    modImplementation("net.fabricmc.fabric-api:fabric-api:${fabric_version}")

    modCompileOnly "dev.emi:trinkets:${trinkets_version}"

    modCompileOnly("io.wispforest:accessories-fabric:${accessories_version}")
    modRuntimeOnly("io.wispforest:accessories-fabric:${accessories_version}")
}

loom {
    def aw = project(':common').file("src/main/resources/${mod_id}.accesswidener")
    if (aw.exists()) {
        accessWidenerPath.set(aw)
    }
    runs {
        client {
            client()
            setConfigName('Fabric Client')
            ideConfigGenerated(true)
            runDir('runs/client')
        }
        server {
            server()
            setConfigName('Fabric Server')
            ideConfigGenerated(true)
            runDir('runs/server')
        }
    }
}

publishMods {
    file.set(remapJar.archiveFile)
    type = STABLE
    modLoaders.add("fabric")
    changelog = rootProject.file("changelog.md").text
    displayName = mod_id + "-" + project.version + "+" + minecraft_version + "-fabric"

    curseforge {
        projectId = "1656564"
        accessToken = findProperty("CF_TOKEN")
        minecraftVersions.add(minecraft_version)
        client = true
        server = true
    }

    modrinth {
        projectId = 'SxtT2MNR'
        accessToken = findProperty("MODRINTH_TOKEN")
        minecraftVersions.add(minecraft_version)
    }
}