# Important Notes:
# Every field you add must be added to buildSrc/src/main/groovy/multiloader-common.gradle expandProps map.

# Project
version=20.1.0
group=com.coolerpromc.craftulator
java_version=17

# Common
minecraft_version=1.20.1
mod_name=Craftulator
mod_author=CoolerProMC
mod_id=craftulator
license=MIT
credits=
description=Add simple calculator item go the game
minecraft_version_range=[1.20.1, 1.20.2)
# The version of ParchmentMC that is used, see https://parchmentmc.org/docs/getting-started#choose-a-version for new versions
parchment_minecraft=1.20.1
parchment_version=2023.09.03

# Fabric, see https://fabricmc.net/develop/ for new versions
fabric_version=0.92.1+1.20.1
fabric_loader_version=0.16.9

# Forge
forge_version=47.4.20
forge_loader_version_range=[47,)

# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

# Dependencies
curios_version=5.14.1+1.20.1
trinkets_version=3.7.2
accessories_version=1.0.0-beta.47+1.20.1